### ISSUE TITLE
Feature request: Create zig-cc, zig-c++ shims

### ISSUE THREAD

**Issue by NoelJacob** [marler8997/zigup#116]
Add option to create shims like these on all platforms zig supports for zig drop-in features : https://github.com/ziglang/zig/issues/8716#issuecomment-1898961470

**Comment by alexrp** [comment]
Is this solution not good enough? https://github.com/ziglang/zig/issues/8716#issuecomment-1511711968 (should be equivalent to `set(CMAKE_C_COMPILER "zig" "cc")` in a toolchain file)

**Comment by NoelJacob** [comment]
Yeah, it's doable but it didn't work for me somewhere in CLion.
