### ISSUE TITLE
zig default master

### ISSUE THREAD

**Issue by marler8997** [marler8997/zigup#33]
The `zig default` command is meant to set the default compiler without fetching it.  In contrast, when referencing the zig `master` version, the latest version is requested from the zig download site each time.  This would mean that `zigup default master` would fail with "compiler not installed" if the website has published a new version since it was last fetched.  That being said, the "spirit" of the default command is not to fetch anything, so in this case, I think it makes more sense to have `zigup default master` set the default compiler to the last master version that was fetched, rather than trying to get the latest version and fail most of the time.

**Comment by cmyka1b2c3d4** [comment]
Having `default` also fetch would have it overlap with `fetch`, no? In other compiler toolchains you explicitly have to pass `update` to, well, update the compiler to latest.
```
# fetch a compiler and set it as the default
zigup <version>
zigup master
zigup 0.6.0
```
Also, having `default` fetch would have it overlap with this as well, no? Kind of speaking out of line here since I have not used zigup in a bit.

**Comment by marler8997** [comment]
Yeah if `zig default VERSION` also fetched, then it would be exactly the same as `zig VERSION`, not very helpful.

**Comment by cmyka1b2c3d4** [comment]
I guess you can have `zig default <VERSION>` fetch only if that version is not installed yet.

**Comment by iddev5** [comment]
@cmyka1b2c3d4 what you are asking for is already done by ``zigup <VERSION>`` command. The spirit of ``zigup default <VERSION>`` is to set the mentioned version as default and show an error if it is not installed, i,e it does not fetch anything in any case.
