### ISSUE TITLE
bin/zig is not created if the path-link directory is not in $PATH

### ISSUE THREAD

**Issue by pfgithub** [marler8997/zigup#82]
```sh
$> zigup 0.11.0-dev.1393+38eebf3c4
install directory '/Users/pfg/zig'
mkdir '/Users/pfg/zig'
compiler '/Users/pfg/zig/0.11.0-dev.1393+38eebf3c4' already installed
error: path-link '/Users/pfg/bin/zig' is lower priority in PATH than '/usr/local/bin/zig'

$> zigup 0.11.0-dev.1393+38eebf3c4
install directory '/Users/pfg/zig'
mkdir '/Users/pfg/zig'
compiler '/Users/pfg/zig/0.11.0-dev.1393+38eebf3c4' already installed
error: the path link '/Users/pfg/bin/zig' is not in PATH
```

Expected:

`~/bin/zig` is still created or updated despite the warning

What happens:

`~/bin/zig` is not created, or if it exists it is not updated

I would expect path issues to be a warning rather than an error, something like:

```sh
$> zigup master
… downloading
Zig installed to ~/bin/zig
warning: ~/bin is not in your PATH. 
or:
warning: There is already a zig compiler in your PATH with higher priority. 
```

**Comment by marler8997** [comment]
I've fixed zigup to update the path symlink even if it's not the highest priority in PATH.  I've still left it as an error for now though since the user is explicitly asking to set the default compiler and they can always skip that request by doing a "zigup fetch VERSION".

**Comment by pfgithub** [comment]
Thanks!
